name: NotEconomy
version: "0.0.1-SNAPSHOT"
main: com.notmarra.noteconomy.NotEconomy
api-version: "1.21"
authors: [NotMarra]
description: The universal economy plugin
website: https://notmarra.com
dependencies:
  server:
    NotLib:
      load: BEFORE
      required: true
